Vagrant.require_version ">= 1.7.0"

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/bionic64"

  # Create a private network for testing
  config.vm.network "private_network", ip: "10.213.213.213"

  config.vm.provision "ansible" do |ansible|
    ansible.extra_vars = {
      ansible_python_interpreter: "/usr/bin/python3"
    }
    ansible.playbook = "playbook.yml"
  end
end
