Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/xenial64"

  # Create a private network for testing
  config.vm.network "private_network", ip: "10.213.213.213"

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "playbook.yml"
  end
end
