# Exercise 03 playbook
- name: Exercise 03 playbook
  hosts: all
  become: yes
  become_user: root

  tasks:
    - name: Install nginx
      apt:
        name: nginx
        state: present

    - include: tasks.yml
